#pragma once

typedef enum {
    GATEWAY_STATUS_OK = 0,
    GATEWAY_STATUS_INVALID_ARG,
    GATEWAY_STATUS_NO_MEM,
    GATEWAY_STATUS_NOT_FOUND,
    GATEWAY_STATUS_NOT_SUPPORTED,
    GATEWAY_STATUS_INVALID_STATE,
    GATEWAY_STATUS_TIMEOUT,
    GATEWAY_STATUS_FAIL,
} gateway_status_t;
